version: "3"

services:
  docusaurus:
    build: .
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./blog:/app/blog
      - ./docs:/app/docs
      - ./src:/app/src
      - ./static:/app/static
      - ./docusaurus.config.js:/app/docusaurus.config.js
      - ./sidebars.js:/app/sidebars.js
    working_dir: /app
